In [3]:
import io
import csv
import pandas as pd

In [34]:
# Assuming you already have the file path
file_path = "RestaurantNamen_Ratings-OSM.csv"

# Open the file and read its content into a BytesIO object
with open(file_path, 'rb') as f:
    file_content = f.read()

# Read a portion of the file content to sniff the dialect
sample = file_content[:1024].decode('utf-8')

# Sniff the dialect
dialect = csv.Sniffer().sniff(sample)

# Create a BytesIO object from the file content
file_like_object = io.BytesIO(file_content)

df = pd.read_csv(file_like_object, dialect=dialect, index_col=index_col, header=header)

In [35]:
df

      RestaurantNameRatings                             OSM
0             Hans im Glück                            Loge
1                     70/30  Hallenbadrestaurant Geiselweid
2    8405 Winterthur - Seen       Schwimmbadrestaurant Töss
3               AL Giardino                          Tibits
4              Am Romerholz                        Kafisatz
..                      ...                             ...
347                     NaN              Ristorante La Rosa
348                     NaN                     Salon Erika
349                     NaN          Transit Laden + Bistro
350                     NaN            Bistro Villa Sträuli
351                     NaN            Pizzeria Don Camillo

[352 rows x 2 columns]

In [31]:
# Create a BytesIO object from the file content
file_like_object = io.BytesIO(file_content)

df = pd.read_csv(file_like_object, dialect=dialect, index_col=index_col, header=header)

In [32]:
index_col=None
header=0

In [33]:
df

      RestaurantNameRatings                             OSM
0             Hans im Glück                            Loge
1                     70/30  Hallenbadrestaurant Geiselweid
2    8405 Winterthur - Seen       Schwimmbadrestaurant Töss
3               AL Giardino                          Tibits
4              Am Romerholz                        Kafisatz
..                      ...                             ...
347                     NaN              Ristorante La Rosa
348                     NaN                     Salon Erika
349                     NaN          Transit Laden + Bistro
350                     NaN            Bistro Villa Sträuli
351                     NaN            Pizzeria Don Camillo

[352 rows x 2 columns]